# Generated by Django 5.0.1 on 2024-01-14 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FlashCardAnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='school.flashcard')),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='school_flas_name_631de8_idx')],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.ManyToManyField(related_name='flascards', to='school.flashcardcategory'),
        ),
        migrations.CreateModel(
            name='FlashcardLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='school_flas_name_acec52_idx')],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='level',
            field=models.ManyToManyField(related_name='flascards', to='school.flashcardlevel'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['-created'], name='school_flas_created_76eaeb_idx'),
        ),
    ]
