# Generated by Django 5.0.1 on 2024-01-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='level',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='level',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Normal'), (3, 'Hard'), (4, 'Master')], default=2),
        ),
    ]
