# Generated by Django 5.0.1 on 2024-02-10 19:37

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="studycategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="category_name_constraint",
            ),
        ),
    ]
