# Generated by Django 5.0.1 on 2024-01-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_flashcard_level_flashcard_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlashcardLevel',
        ),
    ]
