# Generated by Django 5.0.1 on 2024-01-15 14:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_flashcard_user_alter_flashcard_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashCard',
            new_name='ChoicesCard',
        ),
        migrations.RenameModel(
            old_name='FlashCardAnswerOptions',
            new_name='ChoicesCardAnswerOptions',
        ),
        migrations.RenameModel(
            old_name='FlashcardCategory',
            new_name='StudyCategory',
        ),
        migrations.RenameIndex(
            model_name='choicescard',
            new_name='school_choi_created_0ea591_idx',
            old_name='school_flas_created_76eaeb_idx',
        ),
        migrations.RenameIndex(
            model_name='studycategory',
            new_name='school_stud_name_182a5e_idx',
            old_name='school_flas_name_631de8_idx',
        ),
    ]
