# Generated by Django 5.0.1 on 2024-01-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_choicescard_category_alter_choicescard_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
