# Generated by Django 5.0.1 on 2024-01-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_flashcard_user_challenge_challengequestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='questions',
            field=models.ManyToManyField(related_name='challenge_questions', through='school.ChallengeQuestion', to='school.flashcard'),
        ),
    ]
