# Generated by Django 5.0.1 on 2024-01-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_challenge_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='questions',
            field=models.ManyToManyField(related_name='questions', through='school.ChallengeQuestion', to='school.flashcard'),
        ),
    ]
