# Generated by Django 5.0.1 on 2024-01-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_challenge_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='questions',
            new_name='question_set',
        ),
    ]
