# Generated by Django 5.0.1 on 2024-01-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_rename_questions_challenge_question_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='question_set',
        ),
        migrations.AddField(
            model_name='challenge',
            name='questions',
            field=models.ManyToManyField(related_name='question_set', through='school.ChallengeQuestion', to='school.flashcard'),
        ),
    ]
