# Generated by Django 5.0.1 on 2024-01-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_challenge_question_set_challenge_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='questions',
            field=models.ManyToManyField(through='school.ChallengeQuestion', to='school.flashcard'),
        ),
        migrations.AlterField(
            model_name='challengequestion',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_question', to='school.challenge'),
        ),
        migrations.AlterField(
            model_name='challengequestion',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_question', to='school.flashcard'),
        ),
    ]
