# Generated by Django 5.0.1 on 2024-01-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_challenge_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengequestion',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_questions', to='school.challenge'),
        ),
        migrations.AlterField(
            model_name='challengequestion',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_questions', to='school.flashcard'),
        ),
    ]
