# Generated by Django 5.0.1 on 2024-01-21 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0015_alter_challengequestion_challenge_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
