# Generated by Django 5.0.1 on 2024-02-02 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0018_alter_flashcard_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="categories",
            field=models.ManyToManyField(
                related_name="challenges", to="school.studycategory"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="number_questions",
            field=models.PositiveIntegerField(
                verbose_name="Maximun number of questions"
            ),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
