# Generated by Django 5.0.1 on 2024-02-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0019_challenge_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studycategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
