# Generated by Django 5.0.1 on 2024-02-10 00:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0020_alter_studycategory_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choicescardansweroptions",
            name="question",
        ),
        migrations.DeleteModel(
            name="ChoicesCard",
        ),
        migrations.DeleteModel(
            name="ChoicesCardAnswerOptions",
        ),
    ]
